### PR TITLE
Changed some icons to transparent background.

### PR DESCRIPTION
**Pull request by max-programming**
### Before: 
image

### After:
image

### CODE REVIEW

**Comment by EthanDevelops** [comment]
What source did you get your images?

**Comment by max-programming** [comment]
> What source did you get your images from?

I searched the web for it. Filtered it with transparent, copied image address and done

**Comment by EthanDevelops** [comment]
Ok. Got it.

**Comment by max-programming** [comment]
@codeSTACKr I have made this PR because many of the icons you had were without transparent background. They looked bad so I replaced them with good ones. Let me know if I need to change something

**Comment by codeSTACKr** [comment]
I appreciate the effort! I would rather have the GitHub image links than links that may stop working at some point in the future. I trust those more. Thanks again!

**Comment by max-programming** [comment]
Oh Ok. No problem. It's good to use GitHub images. Good decision.

**Pull request closed without merging**
